# Generated by Django 3.1.5 on 2021-02-08 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizzeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('street', models.CharField(max_length=400, validators=[django.core.validators.MinLengthValidator(2)])),
                ('city', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('state', models.CharField(blank=True, max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
                ('zipcode', models.IntegerField(blank=True, default=0)),
                ('website', models.URLField(blank=True, max_length=420)),
                ('phone', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\1?\\d{9,10}$')])),
                ('description', models.TextField(blank=True)),
                ('logo_image', models.ImageField(blank=True, default='pizzariaImages/pizzaLogo.png', upload_to='pizzariaImages')),
                ('email', models.EmailField(blank=True, max_length=256)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
