# Generated by Django 3.1.6 on 2021-02-11 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(2)])),
                ('content', models.CharField(max_length=3000, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
