# Generated by Django 3.1.6 on 2021-02-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='posts',
            field=models.ManyToManyField(to='posts.Tag', verbose_name='posts_tags'),
        ),
    ]
