# Generated by Django 3.1.6 on 2021-02-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210211_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posts',
            field=models.ManyToManyField(blank=True, to='posts.Tag', verbose_name='posts_tags'),
        ),
    ]
